AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-app

    Sample SAM Template for sam-app

Parameters:
    EmailSnsTopicArnPredefined:
        Type: String
        Default: arn:aws:sns:ap-southeast-2:126578846119:about-api-contact-form-dev

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 10
        Environment:
            Variables:
                EMAIL_SNS_TOPIC: !Ref EmailSns
                EMAIL_SNS_TOPIC_PREDEFINED: !Ref EmailSnsTopicArnPredefined


Resources:
    SubmitContactFormFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: dist/
            Handler: contact.postContactForm
            Runtime: nodejs10.x
            Events:
                SubmitContactForm:
                    Type: Api
                    Properties:
                        Path: /contact
                        Method: post
    
    EmailSns:
        Type: AWS::SNS::Topic
        Properties:
            TopicName: about-api-contact-form
            Subscription:
                Endpoint: benjamin.tanone@gmail.com
                Protocol: email

Outputs:

    HelloWorldApi:
      Description: "API Gateway endpoint URL for Prod stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

    HelloWorldFunction:
      Description: "Hello World Lambda Function ARN"
      Value: !GetAtt HelloWorldFunction.Arn

    HelloWorldFunctionIamRole:
      Description: "Implicit IAM Role created for Hello World function"
      Value: !GetAtt HelloWorldFunctionRole.Arn
