AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-app

    Sample SAM Template for sam-app

Parameters:
    EmailSnsTopicArnPredefined:
        Type: String
        Default: arn:aws:sns:ap-southeast-2:126578846119:about-api-contact-form-dev

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 10
        Environment:
            Variables:
                # EMAIL_SNS_TOPIC: !Ref EmailSns
                EMAIL_SNS_TOPIC_PREDEFINED: !Ref EmailSnsTopicArnPredefined


Resources:
    SubmitContactFormFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: dist/
            Handler: contact.handler
            Runtime: nodejs10.x
            Events:
                SubmitContactForm:
                    Type: Api
                    Properties:
                        Path: /contact
                        Method: post
    
    CorsFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: dist/
            Handler: cors.corsHandler
            Runtime: nodejs10.x
            Events:
                SubmitContactForm:
                    Type: Api
                    Properties:
                        Path: /{proxy+}
                        Method: options

    # EmailSns:
    #     Type: AWS::SNS::Topic
    #     Properties:
    #         TopicName: about-api-contact-form
    #         Subscription:
    #             Endpoint: benjamin.tanone@gmail.com
    #             Protocol: email

Outputs:
    ApiBasePath:
      Description: "API Gateway endpoint URL for Prod stage"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

